#!/bin/bash
#PBS -N OpenFOAM_Test
#PBS -l nodes=1,mem=46000MB
#PBS -l walltime=24:00:00
#PBS -M paulmc@vpac.org 
#PBS -m abe
cd $PBS_O_WORKDIR
module purge
module load openfoam/2.1.1
. $foamDotFile
./Allclean
time ./Allrun
echo $PBS_JOBNAME
echo Reference Area
grep Rhino system/forceCoeffs
echo blockMeshDict
grep hexCurrent constant/polyMesh/blockMeshDict
echo snappyHexMeshDict
grep currentRefinement system/snappyHexMeshDict
echo result
tail -n 7 log.simpleFoam
