#!/bin/bash
#PBS -N OpenFOAM_Test
#PBS -l nodes=1,mem=32000MB
#PBS -l walltime=24:00:00
# PBS -M paulmc@vpac.org 
#PBS -m abe
cd $PBS_O_WORKDIR
module purge
module load openfoam/2.1.1
. $foamDotFile
./Allclean
time ./Allrun
echo $PBS_JOBNAME
echo -------------- Reference Area and Speed --------------
grep paulmc system/forceCoeffs
grep paulmc 0.org/include/initialConditions
echo -------------- blockMeshDict --------------
grep paulmc constant/polyMesh/blockMeshDict
echo -------------- snappyHexMeshDict --------------
grep paulmc system/snappyHexMeshDict
echo -------------- result --------------
tail log.simpleFoam
env | grep PBS
