#!/bin/bash
#PBS -N Area_Calc
#PBS -l nodes=1:ppn=2:gpus=2
#PBS -l walltime=0:20:00
#PBS -m abeA
#
# This script does the following
#
# 1) Generates parametric mesh parts
# 2) Assembles the mesh parts into a single STL file called motorBike.stl
# 3) Calculates the frontal area of the final mesh
#
# The result is then used in an OpenFOAM case
cd $PBS_O_WORKDIR
# 1) Generates parametric mesh parts

# 2) Assembles the mesh parts into a single STL file called motorBike.stl

# 3) Calculates the frontal area of the final mesh
module purge
module load baseline/gcc-4.7.0
module load vtk/5.8.0
xinit /home/paulmc/workarea/Vespa-Labs/VespaCFD/CalculateFrontalArea-build-desktop-Qt_in_PATH_Release/CalculateFrontalArea constant/triSurface/motorBike.stl 16 1000 0 0
