#!/bin/bash
#PBS -N OpenFOAM_Test
#PBS -l nodes=1:ppn=2:gpus=2,mem=32000MB
#PBS -l walltime=24:00:00
#PBS -m abe

# some OpenFOAM prep work has been done by pbs_createcase
cd $PBS_O_WORKDIR
echo Run OpenFOAM... 
module purge
module load openfoam/2.1.1
. $foamDotFile
# ./Allclean
# time ./Allrun
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
runApplication `getApplication`

echo $PBS_JOBNAME
echo -------------- Reference Area and Speed --------------
grep paulmc system/forceCoeffs
grep paulmc 0.org/include/initialConditions
echo -------------- blockMeshDict --------------
grep paulmc constant/polyMesh/blockMeshDict
echo -------------- snappyHexMeshDict --------------
grep paulmc system/snappyHexMeshDict
echo -------------- result --------------
tail log.simpleFoam
env | grep PBS
